spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: yuanyang
    password: Yy52101989
    url: jdbc:mysql://mes.api.fuliaoyi.com:3306/fyy_saas_dev?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: true
